openapi: 3.0.3
info:
  title: Building Execution Budget Events
  version: 0.1.0
paths:
  /internal/executor/budget:
    post:
      summary: Emit building execution budget event to dashboard stream
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                timestamp:
                  type: integer
                data:
                  type: object
      responses:
        '200':
          description: accepted
