openapi: 3.1.0
info:
  title: Cognition Observation Processing
  version: "1.0.0"
  description: >-
    Structured contract for minecraft-interface to submit environmental observations
    to the cognition service and receive LLM-authored thoughts plus action guidance.
servers:
  - url: http://localhost:3003
    description: Local cognition service
paths:
  /process:
    post:
      summary: Process cognitive event or observation
      description: >-
        Accepts structured observation payloads for environmental awareness events
        and returns an insight produced by the cognition LLM. Other event types
        continue to be supported but are not described in this contract.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObservationRequest'
      responses:
        '200':
          description: Observation processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObservationInsight'
        '400':
          description: Invalid payload
        '500':
          description: Cognition service failed to process the observation
components:
  schemas:
    ObservationRequest:
      type: object
      required: [type, observation]
      properties:
        type:
          type: string
          const: environmental_awareness
        observation:
          $ref: '#/components/schemas/ObservationPayload'
        metadata:
          type: object
          description: Optional auxiliary metadata preserved for logging/streaming.
        content:
          type: string
          description: Backwards compatibility field ignored when `observation` supplied.
    ObservationPayload:
      type: object
      required: [category, bot, timestamp]
      properties:
        observationId:
          type: string
          description: Client generated id for traceability.
        category:
          type: string
          enum: [entity, environment]
        bot:
          type: object
          required: [position, health, food, dimension]
          properties:
            position:
              $ref: '#/components/schemas/Vec3'
            health:
              type: number
            food:
              type: number
            dimension:
              type: string
            gameMode:
              type: string
        entity:
          $ref: '#/components/schemas/EntitySnapshot'
        event:
          $ref: '#/components/schemas/EventSnapshot'
        context:
          type: object
          description: Additional environment or planner context.
        timestamp:
          type: integer
          format: int64
    EntitySnapshot:
      type: object
      required: [id, name, position, distance]
      properties:
        id:
          type: string
        name:
          type: string
        displayName:
          type: string
        kind:
          type: string
        threatLevel:
          type: string
          enum: [unknown, neutral, friendly, hostile]
        distance:
          type: number
        position:
          $ref: '#/components/schemas/Vec3'
        velocity:
          $ref: '#/components/schemas/Vec3'
    EventSnapshot:
      type: object
      properties:
        type:
          type: string
        description:
          type: string
        position:
          $ref: '#/components/schemas/Vec3'
        severity:
          type: string
    Vec3:
      type: object
      required: [x, y, z]
      properties:
        x:
          type: number
        y:
          type: number
        z:
          type: number
    ObservationInsight:
      type: object
      required: [processed, type, timestamp]
      properties:
        processed:
          type: boolean
        type:
          type: string
          const: environmental_awareness
        timestamp:
          type: integer
          format: int64
        observationId:
          type: string
        thought:
          $ref: '#/components/schemas/ObservationThought'
        actions:
          $ref: '#/components/schemas/ObservationActions'
        fallback:
          type: boolean
          description: Indicates heuristic fallback was used instead of LLM output.
        error:
          type: string
          description: Present when processing failed.
    ObservationThought:
      type: object
      required: [text, source]
      properties:
        text:
          type: string
        source:
          type: string
          enum: [llm, fallback]
        confidence:
          type: number
        categories:
          type: array
          items:
            type: string
    ObservationActions:
      type: object
      required: [shouldRespond, shouldCreateTask]
      properties:
        shouldRespond:
          type: boolean
        response:
          type: string
        shouldCreateTask:
          type: boolean
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/ObservationTask'
    ObservationTask:
      type: object
      required: [description, priority, source]
      properties:
        description:
          type: string
        priority:
          type: number
        urgency:
          type: number
        source:
          type: string
          enum: [llm, fallback]
        metadata:
          type: object
    # ── Saliency Delta Stream Contract ───────────────────────────
    SaliencyDeltaRequest:
      type: object
      required: [request_version, type, bot_id, stream_id, seq, tick_id, saliency_events]
      description: >-
        Belief-stream envelope sent by minecraft-interface at 1Hz.
        Routes via request_version discriminator to the saliency reasoner.
      properties:
        request_version:
          type: string
          const: saliency_delta
        type:
          type: string
          const: environmental_awareness
        bot_id:
          type: string
          description: >-
            Stable bot identity (e.g. 'bot-steve'). Does not change across
            restarts. Used by cognition to key per-bot state without regex
            parsing of stream_id.
        stream_id:
          type: string
          description: >-
            Ephemeral stream identity. Changes on every bot instantiation
            (e.g. 'bot-steve-1', 'bot-steve-2'). Cognition uses (bot_id, stream_id)
            to detect restarts.
        seq:
          type: integer
          description: Monotonically increasing sequence number per stream_id.
        tick_id:
          type: integer
          description: Monotonic tick counter from the belief ingestion loop.
        snapshot:
          $ref: '#/components/schemas/TrackSetSnapshot'
        saliency_events:
          type: array
          items:
            $ref: '#/components/schemas/SaliencyDelta'
    SaliencyDelta:
      type: object
      required: [type, trackId, classLabel, threatLevel, distBucket]
      properties:
        type:
          type: string
          enum: [new_threat, track_lost, reclassified, movement_bucket_change]
        trackId:
          type: string
          description: Content-addressed track identifier.
        classLabel:
          type: string
        threatLevel:
          type: string
          enum: [none, low, medium, high, critical]
        distBucket:
          type: integer
        prev:
          type: object
          properties:
            threatLevel:
              type: string
              enum: [none, low, medium, high, critical]
            distBucket:
              type: integer
        track:
          $ref: '#/components/schemas/TrackSummary'
          description: >-
            Full track state, included on new_threat so cognition can hydrate
            without waiting for the next snapshot. Required for new_threat deltas;
            absence is treated as a schema violation (fail-closed).
    LineOfSight:
      type: string
      enum: [visible, occluded, unknown]
      description: Line-of-sight evidence quality vocabulary.
    EvidenceItem:
      type: object
      required: [engineId, kind, kindEnum, posBucketX, posBucketY, posBucketZ, distBucket, los]
      properties:
        engineId:
          type: integer
        kind:
          type: string
        kindEnum:
          type: integer
        posBucketX:
          type: integer
        posBucketY:
          type: integer
        posBucketZ:
          type: integer
        distBucket:
          type: integer
        los:
          $ref: '#/components/schemas/LineOfSight'
        features:
          type: object
          additionalProperties: true
    TrackSetSnapshot:
      type: object
      required: [tickId, tracks]
      properties:
        tickId:
          type: integer
        tracks:
          type: array
          items:
            $ref: '#/components/schemas/TrackSummary'
    TrackSummary:
      type: object
      required: [trackId, classLabel, kindEnum, posBucketX, posBucketY, posBucketZ, distBucket, visibility, threatLevel, confidence, firstSeenTick, lastSeenTick]
      properties:
        trackId:
          type: string
        classLabel:
          type: string
        kindEnum:
          type: integer
        posBucketX:
          type: integer
        posBucketY:
          type: integer
        posBucketZ:
          type: integer
        distBucket:
          type: integer
        visibility:
          type: string
          enum: [visible, inferred, lost]
        threatLevel:
          type: string
          enum: [none, low, medium, high, critical]
        confidence:
          type: number
          minimum: 0
          maximum: 1
        pUnknown:
          type: number
          minimum: 0
          maximum: 1
          description: >-
            Classification uncertainty: probability mass representing
            "don't know what this is". When > 0.5, threatLevel drops to 'none'.
        firstSeenTick:
          type: integer
        lastSeenTick:
          type: integer
